import type { User, Report } from './types';

export const users: User[] = [
  {
    uid: 'citizen-01',
    email: 'jane.doe@example.com',
    fullName: 'Jane Doe',
    role: 'citizen',
  },
  {
    uid: 'authority-01',
    email: 'john.smith@city.gov',
    fullName: 'John Smith',
    role: 'authority',
  },
];

export const reports: Report[] = [
  {
    reportId: 'rep-001',
    userId: 'citizen-01',
    userFullName: 'Jane Doe',
    imageUrl: 'https://picsum.photos/seed/pothole1/400/300',
    imageHint: 'road pothole',
    issueType: 'Pothole',
    severity: 'High',
    aiDescription: 'A significant pothole is present in the road surface, posing a potential hazard to vehicles. It appears to be deep and has sharp edges.',
    status: 'Submitted',
    location: { lat: 34.0522, lng: -118.2437 },
    createdAt: '2024-07-28T10:00:00Z',
  },
  {
    reportId: 'rep-002',
    userId: 'citizen-01',
    userFullName: 'Jane Doe',
    imageUrl: 'https://picsum.photos/seed/graffiti1/400/300',
    imageHint: 'wall graffiti',
    issueType: 'Graffiti',
    severity: 'Low',
    aiDescription: 'Spray-painted graffiti is visible on a public brick wall. The content is non-offensive but aesthetically disruptive.',
    status: 'In Progress',
    authorityId: 'authority-01',
    location: { lat: 34.055, lng: -118.25 },
    createdAt: '2024-07-27T15:30:00Z',
  },
  {
    reportId: 'rep-003',
    userId: 'citizen-01',
    userFullName: 'Jane Doe',
    imageUrl: 'https://picsum.photos/seed/garbage1/400/300',
    imageHint: 'overflowing trash',
    issueType: 'Waste Management',
    severity: 'Medium',
    aiDescription: 'A public trash bin is overflowing, with litter scattered on the surrounding pavement. This requires immediate attention to prevent further spread.',
    status: 'Resolved',
    authorityId: 'authority-01',
    resolvedImageUrl: 'https://picsum.photos/seed/pothole-resolved/400/300',
    resolvedImageHint: 'clean street',
    location: { lat: 34.048, lng: -118.24 },
    createdAt: '2024-07-26T09:00:00Z',
  },
  {
    reportId: 'rep-004',
    userId: 'citizen-01',
    userFullName: 'Jane Doe',
    imageUrl: 'https://picsum.photos/seed/light1/400/300',
    imageHint: 'broken streetlight',
    issueType: 'Broken Streetlight',
    severity: 'Medium',
    aiDescription: 'A streetlight is not functioning, creating a dark spot on the street at night. This could be a safety concern for pedestrians and drivers.',
    status: 'Submitted',
    location: { lat: 34.06, lng: -118.26 },
    createdAt: '2024-07-29T21:00:00Z',
  },
];
