[build]
  command = "npx next build"
  publish = ".next"

[build.environment]
  # Add your environment variables here for Netlify deployment
  # GEMINI_API_KEY = "YOUR_GEMINI_API_KEY"

[[plugins]]
  package = "@netlify/plugin-nextjs"
